AWSTemplateFormatVersion: '2010-09-09'
Description: 'Food Ordering API - Lambda and API Gateway'

Parameters:
  TwilioAccountSid:
    Type: String
    Description: Twilio Account SID
    NoEcho: true
  
  TwilioAuthToken:
    Type: String
    Description: Twilio Auth Token
    NoEcho: true
  
  TwilioWhatsAppNumber:
    Type: String
    Default: 'whatsapp:+14155238886'
  
  TwilioSmsNumber:
    Type: String
  
  RestaurantWhatsAppNumber:
    Type: String
    Default: 'whatsapp:+919766007557'
  
  RestaurantSmsNumber:
    Type: String
    Default: '+919766007557'

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  # Lambda Function
  NotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: food-ordering-notifications
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          const https = require('https');
          
          exports.handler = async (event) => {
            console.log('Event:', JSON.stringify(event));
            
            const body = JSON.parse(event.body || '{}');
            const { orderDetails, customerPhone } = body;
            
            const twilioAccountSid = process.env.TWILIO_ACCOUNT_SID;
            const twilioAuthToken = process.env.TWILIO_AUTH_TOKEN;
            const twilioWhatsApp = process.env.TWILIO_WHATSAPP_NUMBER;
            const twilioSms = process.env.TWILIO_SMS_NUMBER;
            const restaurantWhatsApp = process.env.RESTAURANT_WHATSAPP_NUMBER;
            
            // Format message
            const message = `🔔 NEW ORDER!\n\nOrder ID: ${orderDetails.orderId}\nCustomer: ${orderDetails.customerName}\nPhone: ${customerPhone}\nItems: ${orderDetails.items}\nTotal: ₹${orderDetails.total}\nAddress: ${orderDetails.address}`;
            
            // Send WhatsApp to restaurant
            try {
              await sendTwilioMessage(
                twilioAccountSid,
                twilioAuthToken,
                twilioWhatsApp,
                restaurantWhatsApp,
                message
              );
              
              // Send SMS to customer
              const customerMessage = `Thank you for your order! Order ID: ${orderDetails.orderId}. Total: ₹${orderDetails.total}. We'll deliver in 30 minutes.`;
              await sendTwilioMessage(
                twilioAccountSid,
                twilioAuthToken,
                twilioSms,
                customerPhone,
                customerMessage
              );
              
              return {
                statusCode: 200,
                headers: {
                  'Access-Control-Allow-Origin': '*',
                  'Access-Control-Allow-Headers': 'Content-Type',
                  'Access-Control-Allow-Methods': 'POST,OPTIONS'
                },
                body: JSON.stringify({ success: true, message: 'Notifications sent' })
              };
            } catch (error) {
              console.error('Error:', error);
              return {
                statusCode: 500,
                headers: {
                  'Access-Control-Allow-Origin': '*'
                },
                body: JSON.stringify({ success: false, error: error.message })
              };
            }
          };
          
          function sendTwilioMessage(accountSid, authToken, from, to, body) {
            return new Promise((resolve, reject) => {
              const auth = Buffer.from(`${accountSid}:${authToken}`).toString('base64');
              const postData = new URLSearchParams({
                From: from,
                To: to,
                Body: body
              }).toString();
              
              const options = {
                hostname: 'api.twilio.com',
                port: 443,
                path: `/2010-04-01/Accounts/${accountSid}/Messages.json`,
                method: 'POST',
                headers: {
                  'Authorization': `Basic ${auth}`,
                  'Content-Type': 'application/x-www-form-urlencoded',
                  'Content-Length': postData.length
                }
              };
              
              const req = https.request(options, (res) => {
                let data = '';
                res.on('data', (chunk) => data += chunk);
                res.on('end', () => {
                  if (res.statusCode === 201) {
                    resolve(JSON.parse(data));
                  } else {
                    reject(new Error(`Twilio error: ${data}`));
                  }
                });
              });
              
              req.on('error', reject);
              req.write(postData);
              req.end();
            });
          }
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_WHATSAPP_NUMBER: !Ref TwilioWhatsAppNumber
          TWILIO_SMS_NUMBER: !Ref TwilioSmsNumber
          RESTAURANT_WHATSAPP_NUMBER: !Ref RestaurantWhatsAppNumber
          RESTAURANT_SMS_NUMBER: !Ref RestaurantSmsNumber

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: food-ordering-api
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - '*'

  # Lambda Integration
  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt NotificationFunction.Arn
      PayloadFormatVersion: '2.0'

  # API Route
  ApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: 'POST /send-notification'
      Target: !Sub 'integrations/${ApiIntegration}'

  # API Stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: '$default'
      AutoDeploy: true

  # Lambda Permission
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NotificationFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com'
  
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref NotificationFunction
